"""Parser for containerlab /etc/hosts blocks and centralized hosts merge."""

from __future__ import annotations

import ipaddress
import logging
import re
from dataclasses import dataclass

from dnlab_multinode.services.ssh import SSHClient

log = logging.getLogger(__name__)


@dataclass(frozen=True)
class HostEntry:
    """A single DNS-worthy entry: name → (family, ip)."""
    name: str
    ip: str
    family: str   # "A" (ipv4) or "AAAA" (ipv6)


def parse_hosts_block(text: str, lab_name: str) -> list[HostEntry]:
    """Extract (ip, name) tuples from the containerlab /etc/hosts block.

    The block is delimited by::

        ###### CLAB-<labname>-START ######
        ...
        ###### CLAB-<labname>-END ######

    Each line inside is::

        <ip>  <hostname>  <container_hash>  # Kind: <kind>

    The hash and the comment are ignored.

    Note: the marker prefix is ``CLAB-`` because containerlab itself writes
    these blocks — the prefix is hardcoded upstream and unaffected by the
    dnlab rebrand.
    """
    start_re = re.compile(rf"^#+\s*CLAB-{re.escape(lab_name)}-START\s*#+\s*$")
    end_re = re.compile(rf"^#+\s*CLAB-{re.escape(lab_name)}-END\s*#+\s*$")

    entries: list[HostEntry] = []
    inside = False

    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue

        if start_re.match(line):
            inside = True
            continue
        if end_re.match(line):
            inside = False
            continue
        if not inside:
            continue

        # Strip inline comment
        payload = line.split("#", 1)[0].strip()
        if not payload:
            continue

        parts = payload.split()
        if len(parts) < 2:
            continue

        ip_str, name = parts[0], parts[1]

        try:
            addr = ipaddress.ip_address(ip_str)
        except ValueError:
            log.debug("Skipping invalid IP in hosts block: %s", ip_str)
            continue

        family = "AAAA" if addr.version == 6 else "A"
        entries.append(HostEntry(name=name, ip=ip_str, family=family))

    return entries


def collect_hosts_entries(
    lab_name: str,
    clients: dict[str, SSHClient],
) -> list[HostEntry]:
    """Read /etc/hosts from every host and merge the lab's block.

    Order: master first, then workers alphabetically (for deterministic
    dedup-by-first-wins). Duplicates logged as warnings.

    Args:
        lab_name: lab name (matches the containerlab block marker)
        clients: {host_name: SSHClient} — must be connected

    Returns: deduplicated list of HostEntry
    """
    ordered_hosts: list[str] = []
    if "master" in clients:
        ordered_hosts.append("master")
    ordered_hosts.extend(sorted(h for h in clients if h != "master"))

    seen: dict[str, HostEntry] = {}

    for host_name in ordered_hosts:
        client = clients[host_name]
        try:
            text = client.run("cat /etc/hosts", check=False)
        except Exception as e:
            log.warning("[%s] Cannot read /etc/hosts: %s", host_name, e)
            continue

        entries = parse_hosts_block(text, lab_name)
        log.info("[%s] Found %d DNLAB hosts entries for lab '%s'",
                 host_name, len(entries), lab_name)

        for entry in entries:
            if entry.name in seen:
                existing = seen[entry.name]
                if existing.ip != entry.ip:
                    log.warning(
                        "Duplicate name '%s' across hosts: %s (kept) vs %s (on %s)",
                        entry.name, existing.ip, entry.ip, host_name,
                    )
                continue
            seen[entry.name] = entry

    return list(seen.values())


def render_hosts_file(entries: list[HostEntry]) -> str:
    """Build a dnsmasq-compatible hosts file body."""
    lines = [
        "# Generated by dnlab-multinode — centralized DNS zone",
        "# Format: <ip>  <hostname>",
        "",
    ]
    for entry in sorted(entries, key=lambda e: (e.family, e.name)):
        lines.append(f"{entry.ip:<40} {entry.name}")
    lines.append("")
    return "\n".join(lines)


def get_upstream_dns(client: SSHClient) -> list[str]:
    """Read upstream nameservers from the host's /etc/resolv.conf.

    Filters out IPv4 loopback stubs (e.g. systemd-resolved 127.0.0.53). If no
    usable nameserver is found, returns the fallback ``["1.1.1.1"]``.
    """
    try:
        out = client.run(
            "grep -E '^[[:space:]]*nameserver' /etc/resolv.conf || true",
            check=False,
        )
    except Exception as e:
        log.warning("Cannot read /etc/resolv.conf: %s — fallback to 1.1.1.1", e)
        return ["1.1.1.1"]

    servers: list[str] = []
    for line in out.splitlines():
        parts = line.strip().split()
        if len(parts) >= 2 and parts[0] == "nameserver":
            addr = parts[1]
            try:
                ip = ipaddress.ip_address(addr)
            except ValueError:
                continue
            # Skip IPv4 loopback stub resolvers
            if ip.version == 4 and ip.is_loopback:
                log.debug("Skipping loopback resolver: %s", addr)
                continue
            servers.append(addr)

    if not servers:
        log.warning("No usable upstream DNS from /etc/resolv.conf — fallback to 1.1.1.1")
        return ["1.1.1.1"]

    log.info("Upstream DNS from master: %s", servers)
    return servers
